version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: discovery-graphs-dashboard
    environment:
      - MONGO_INITDB_ROOT_USERNAME=discovery-graphs-dashboard
      - MONGO_INITDB_ROOT_PASSWORD=VMjNgJoBu3S2ZgBw
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: